version: "3.9"

services:
  app:
    build: .
    # entrypoint: ./.docker/entrypoint.sh
    container_name: ${PROJECT_NAME}-api
    volumes:
      - .:/go/src
    ports:
      - "8091:8091"
    restart: on-failure
    networks:
      - backend-net
      - kafka-net

networks:
  backend-net:
    external: true
  kafka-net:
    external: true
