version: "3.9"

services:
  app:
    build: .
    # entrypoint: ./.docker/entrypoint.sh
    container_name: ${PROJECT_NAME}-api
    volumes:
      - .:/go/src
    ports:
      - "8001:8001"
    restart: on-failure
